source 'https://rubygems.org'

gem 'rack-cors'

gem 'rails', '~> 5.0.0', '>= 5.0.0.1'

gem 'spring', :group => :development

gem 'devise'

gem 'pg'

gem 'sdoc', '~> 0.4.0', group: :doc
gem 'thin'

group :development, :test do
    gem 'faker'
    gem 'byebug'
    gem 'web-console', '~> 2.0'
    gem 'spring'
    gem 'listen'
end



# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
